name: Nightly Build dicts

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: "0 14 * * *" # 每天晚上 10 点

concurrency: # 防止并发冲突
  group: nightly-release
  cancel-in-progress: true

jobs:
  nightly-release:
    runs-on: ubuntu-22.04

    steps:
      # ✅ 1. 检出当前仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ 2. 下载固定 Release 文件
      - name: Download wanxiang-lts-zh-hans.gram
        run: |
          FILE_URL="https://github.com/amzxyz/RIME-LMDG/releases/download/dict-nightly/wanxiang-lts-zh-hans.gram"
          wget -O wanxiang-lts-zh-hans.gram "$FILE_URL"
          ls -lah wanxiang-lts-zh-hans.gram # 确保文件下载成功

      # ✅ 3. 打包 cn_dicts.zip（不包含 wanxiang-lts-zh-hans.gram）
      - name: Pack cn_dicts
        run: |
          mkdir -p dist
          if [ -d "cn_dicts" ]; then
            zip -r dist/cn_dicts.zip cn_dicts
            echo "✅ Packing completed: dist/cn_dicts.zip"
          else
            echo "❌ Error: cn_dicts folder does not exist."
            exit 1
          fi

      # ✅ 4. 删除旧的 Release 和 Tag（如果存在）
      - name: Delete existing Nightly Release and Tag
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = "dict-nightly";
            try {
              const releases = await github.rest.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo
              });

              const existingRelease = releases.data.find(r => r.tag_name === tag);
              if (existingRelease) {
                console.log(`Deleting existing Release with ID: ${existingRelease.id}`);
                await github.rest.repos.deleteRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  release_id: existingRelease.id
                });
              }

              console.log(`Deleting tag: ${tag}`);
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${tag}`
              });
            } catch (error) {
              console.log(`No existing Release/Tag found or failed to delete: ${error.message}`);
            }

      # ✅ 5. 等待 GitHub 清理旧数据
      - name: Wait for cleanup
        run: sleep 10

      # ✅ 6. 创建新的 Release，并上传 `cn_dicts.zip` 和 `wanxiang-lts-zh-hans.gram`
      - name: Create new Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: dict-nightly
          name: "每夜构建-词库更新"
          body: |
            - `cn_dicts.zip`：最新的中文词库文件。
            - `wanxiang-lts-zh-hans.gram`：最新的语法模型文件。
          files: |
            dist/cn_dicts.zip
            wanxiang-lts-zh-hans.gram
          draft: false
          prerelease: false
          make_latest: true
