name: Nightly Build dicts

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: "0 14 * * *" # 每天晚上 10 点

concurrency: # 防止并发冲突
  group: nightly-release
  cancel-in-progress: true

jobs:
  nightly-release:
    runs-on: ubuntu-22.04

    steps:
      # ✅ 1. 检出当前仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ 2. 获取 "source-repo" 的最新 Release 文件 URL
      - name: Get latest release from source repo
        id: get_source_release
        run: |
          SOURCE_REPO="amzxyz/RIME-LMDG" # ⚠️ 这里替换为你的目标仓库
          FILE_NAME="wanxiang-lts-zh-hans.gram" # 需要获取的文件名

          # 获取最新 Release 的下载 URL
          API_URL="https://api.github.com/repos/$SOURCE_REPO/releases/latest"
          DOWNLOAD_URL=$(curl -s $API_URL | jq -r ".assets[] | select(.name==\"$FILE_NAME\") | .browser_download_url")

          if [ -z "$DOWNLOAD_URL" ]; then
            echo "❌ 未找到 $FILE_NAME，终止运行"
            exit 1
          fi

          echo "🔗 下载地址: $DOWNLOAD_URL"
          echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV

      # ✅ 3. 下载该文件
      - name: Download release file
        run: |
          wget -O wanxiang-lts-zh-hans.gram "$DOWNLOAD_URL"
          ls -lah wanxiang-lts-zh-hans.gram # 确保文件下载成功

      # ✅ 4. 打包 cn_dicts.zip（不包含 wanxiang-lts-zh-hans.gram）
      - name: Pack cn_dicts
        run: |
          mkdir -p dist
          if [ -d "cn_dicts" ]; then
            zip -r dist/cn_dicts.zip cn_dicts
            echo "✅ Packing completed: dist/cn_dicts.zip"
          else
            echo "❌ Error: cn_dicts folder does not exist."
            exit 1
          fi

      # ✅ 5. 删除旧的 Release 和 Tag（如果存在）
      - name: Delete existing Nightly Release and Tag
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = "dict-nightly";
            try {
              const releases = await github.rest.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo
              });

              const existingRelease = releases.data.find(r => r.tag_name === tag);
              if (existingRelease) {
                console.log(`Deleting existing Release with ID: ${existingRelease.id}`);
                await github.rest.repos.deleteRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  release_id: existingRelease.id
                });
              }

              console.log(`Deleting tag: ${tag}`);
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${tag}`
              });
            } catch (error) {
              console.log(`No existing Release/Tag found or failed to delete: ${error.message}`);
            }

      # ✅ 6. 等待 GitHub 清理旧数据
      - name: Wait for cleanup
        run: sleep 10

      # ✅ 7. 创建新的 Release，并上传 `cn_dicts.zip` 和 `wanxiang-lts-zh-hans.gram`
      - name: Create new Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: dict-nightly
          name: "每夜构建-词库更新"
          body: |
            - `cn_dicts.zip`：最新的中文词库文件。
            - `wanxiang-lts-zh-hans.gram`：从外部仓库获取的最新语法文件。
          files: |
            dist/cn_dicts.zip
            wanxiang-lts-zh-hans.gram
          draft: false
          prerelease: false
          make_latest: true
