name: Release Standard Version

on:
  push:
    tags:
      - 'v*'   # 触发：以 v 开头的标签，如 v1.0.0

concurrency:
  group: release-standard
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置打包环境（Node 仅为 GH Release 工具需要）
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. 打包所需内容
      - name: Pack release contents into rime-wanxiang.zip
        run: |
          mkdir -p dist
          # 查找所有符合条件的根目录文件
          ROOT_FILES=$(find . -maxdepth 1 -type f \( -iname "*.yaml" -o -iname "*.txt" -o -iname "*.ini" -o -iname "*.md" -o -iname "*.png" -o -iname "*.jpg" \) \
            ! -iname "wanxiang_pro*" ! -iname "wanxiang_lookup*" ! -iname "wanxiang_charset*")
      
          # 打包所有内容
          zip -r dist/rime-wanxiang.zip \
            custom/wanxiang.custom.yaml \
            custom/wanxiang_en.custom.yaml \
            custom/wanxiang_radical.custom.yaml \
            en_dicts \
            jm_dicts \
            lua \
            opencc \
            zh_dicts \
            $ROOT_FILES
    

      # 3.5 提取当前 tag 版本号
      - name: Extract tag version
        id: extract_tag
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # 3.6 生成更新说明（changelog）
      - name: Generate changelog from commits
        run: |
          echo "### 📦 下载导航" > release_notes.md
          echo "---" >> release_notes.md
          echo "" >> release_notes.md
          echo "#### 1. 标准版输入方案" >> release_notes.md
          echo "✨**适用类型：** 支持全拼、各种双拼" >> release_notes.md
          echo "✨**下载地址：** [rime-wanxiang.zip](https://github.com/${{ github.repository }}/releases/download/${{ env.TAG_VERSION }}/rime-wanxiang.zip)" >> release_notes.md
          echo "" >> release_notes.md
          echo "#### 2. 双拼辅助码增强版输入方案" >> release_notes.md
          echo "✨**适用类型：** 支持各种双拼+辅助码的自由组合" >> release_notes.md
          for type in zrm moqi flypy jdh hanxin wubi tiger; do
            echo "- **${type^^} 辅助版本：** [rime-wanxiang-${type}-fuzhu.zip](https://github.com/${{ github.repository }}/releases/download/${{ env.TAG_VERSION }}/rime-wanxiang-${type}-fuzhu.zip)" >> release_notes.md
          done
          echo "" >> release_notes.md
          echo "#### 3. 语法模型" >> release_notes.md
          echo "✨**适用类型：** 所有版本皆可用" >> release_notes.md
          echo "✨**下载地址：** [wanxiang-lts-zh-hans.gram](https://github.com/amzxyz/RIME-LMDG/releases/download/LTS/wanxiang-lts-zh-hans.gram)" >> release_notes.md
          echo "" >> release_notes.md
          echo "#### 📝 更新日志" >> release_notes.md
          echo "" >> release_notes.md
          git log --pretty=format:"- %s (%an)" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> release_notes.md
          echo "" >> release_notes.md
          echo "---" >> release_notes.md
          echo "📖 使用说明与配置教程请查看仓库中的 README.md" >> release_notes.md

      # 4. 创建 GitHub Release 并上传打包文件
      - name: Create Release and Upload
        uses: softprops/action-gh-release@v2
        with:
          files: dist/rime-wanxiang.zip
          body_path: release_notes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
